### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-webcrypt-tests#2]
```
============================================================================================= short test summary info =============================================================================================
FAILED test_comm.py::test_generate_from_data - assert False == True
FAILED test_comm.py::test_initialize - assert False == True
FAILED test_comm.py::test_restore[test_input0] - assert False == True
FAILED test_comm.py::test_restore[test_input1] - assert False == True
FAILED test_comm.py::test_restore[test_input2] - assert False == True
FAILED test_comm.py::test_logout - assert True == False
FAILED test_comm.py::test_factory_reset - assert False == True
========================================================================================== 7 failed, 62 passed in 20.34s ==========================================================================================
```

Environment:
- Pipfile modified to use Python 3.9
- firmware 9343983 with `DEVELOP=1`
- `REAL_HARDWARE=1 TRANSPORT=FIDO2`

Log: https://cloud.nitrokey.com/s/nyip4TwAesAwaff

---------------

Edit the same as local archives:
[webcrypt-report-fido2-usb.zip](https://github.com/Nitrokey/nitrokey-webcrypt-tests/files/9506440/webcrypt-report-fido2-usb.zip)
[webcrypt-report-u2f-usb.zip](https://github.com/Nitrokey/nitrokey-webcrypt-tests/files/9506441/webcrypt-report-u2f-usb.zip)

**Comment by robin-nitrokey** [comment]
Looks like the same errors occur with `TRANSPORT=U2F`: https://cloud.nitrokey.com/s/faWwi2MtY39Lqes

**Comment by szszszsz** [comment]
This looks like an old Webcrypt version was used. Can you link here the commit version of the firmware you used?
I will add version string logging to the tests next time.

**Comment by robin-nitrokey** [comment]
> Can you link here the commit version of the firmware you used?

I listed the firmware version in the issue description, it’s [9343983](https://github.com/Nitrokey/nitrokey-3-firmware/commit/9343983) in this case.
