### ISSUE TITLE
Test failure via NFC

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-webcrypt-tests#3]
```
64 failed, 5 passed in 5.08s 
```

Environment:
- Pipfile modified to use Python 3.9 and patched pynitrokey for NFC support
- firmware 9343983 with `DEVELOP=1` and updated to use `fido-authenticator` v0.1.1
- `REAL_HARDWARE=1 TRANSPORT=FIDO2`

Log: https://cloud.nitrokey.com/s/rkNjNb35cLsdKr9

**Comment by szszszsz** [comment]
This looks like a libfido2 version problem. AFAIR it still uses the old API. Can you try installing `fido2==0.8`  or `0.9` ?
I will check the project file for the proper library requirements.

```python

>       return cls(**kwargs)
E       TypeError: __init__() missing 1 required positional argument: 'credential'

../../../.local/share/virtualenvs/nitrokey-webcrypt-tests-9V2q4MSs/lib/python3.9/site-packages/fido2/utils.py:251: TypeError
```
