### ISSUE TITLE
USB, U2F: test_logout and test_factory_reset fail

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-webcrypt-tests#5]
Follow-up from #2 – most issues seem to be fixed, except:

```
FAILED test_comm.py::test_logout - assert True == False
FAILED test_comm.py::test_factory_reset - assert 253 == 240
```

Environment:
- tests 90ad5e6
- firmware 9343983 with `DEVELOP=1` and updated to use `fido-authenticator` v0.1.1
- `REAL_HARDWARE=1 TRANSPORT=U2F`

[report](https://github.com/Nitrokey/nitrokey-webcrypt-tests/files/9549262/webcrypt-u2f-usb.zip)

**Comment by szszszsz** [comment]
This requires update of the WebCrypt library to the latest. Will make a proper release in a moment.

**Comment by szszszsz** [comment]
Please check again with https://github.com/Nitrokey/nitrokey-3-firmware/commit/2136a72eb33845541f6ca5de5c56f48bcfd27493

**Comment by robin-nitrokey** [comment]
```
========================================= 69 passed in 22.02s ==========================================
```

Environment:
- tests 4871460
- firmware 2136a72 with `DEVELOP=1`
- `REAL_HARDWARE=1 TRANSPORT=U2F`

[report](https://github.com/Nitrokey/nitrokey-webcrypt-tests/files/9549433/webcrypt-u2f-usb.zip)
