### ISSUE TITLE
test_decrypt[True] fails

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-webcrypt-tests#9]
```
======================================= short test summary info ========================================
FAILED test_comm.py::test_decrypt[True] - assert False == True
==================================== 1 failed, 68 passed in 22.13s =====================================
```

- tests 4871460
- firmware 7de4dc0 with DEVELOP=1
- configurations
  - U2F over USB
  - FIDO2 over NFC
 
[reports.zip](https://github.com/Nitrokey/nitrokey-webcrypt-tests/files/9647947/reports.zip)

**Comment by robin-nitrokey** [comment]
setup description:
- NFC reader: Identiv uTrust 3700 F CL Reader
- hardware: NK3CN with lpc55
- firmware: https://github.com/Nitrokey/nitrokey-3-firmware/commit/7de4dc0ea8d29af47eedbf03a016cdb9ac460460 with DEVELOP=1
- tests: https://github.com/Nitrokey/nitrokey-webcrypt-tests/commit/48714604ba74cfcf9cd97d20263048b5ab9a8fbe
- OS: Debian 11
- software:
  - Python 3.9.2
  - Python library versions: see `Pipfile.lock` in the tests repository
  - pcscd 1.9.1

**Comment by szszszsz** [comment]
Direct cause:
- trussed-34d232ec9a779a47/29cdbe7/src/mechanisms/aes256cbc.rs:113
> return Err(Error::WrongKeyKind);

Expected: `Symmetric`, found `Shared`

**Comment by szszszsz** [comment]
Fixed with https://github.com/Nitrokey/nitrokey-webcrypt-rust/commit/d378f5e0106e6f7067c9af1c8be3aa5cbbfbce20
Related: https://github.com/trussed-dev/trussed/pull/43

**Comment by robin-nitrokey** [comment]
```
========================================= 69 passed in 30.88s ==========================================
```

setup description:
- NFC reader: Identiv uTrust 3700 F CL Reader
- hardware: NK3CN with lpc55
- firmware: https://github.com/Nitrokey/nitrokey-3-firmware/commit/61a4b729c617de302ae62bbc933759edde6611ab with DEVELOP=1
- tests: https://github.com/Nitrokey/nitrokey-webcrypt-tests/commit/48714604ba74cfcf9cd97d20263048b5ab9a8fbe
- OS: Debian 11
- software:
  - Python 3.9.2
  - Python library versions: see `Pipfile.lock` in the tests repository
  - pcscd 1.9.1

[nfc-fido2.zip](https://github.com/Nitrokey/nitrokey-webcrypt-tests/files/9675948/nfc-fido2.zip)
[firmware.zip](https://github.com/Nitrokey/nitrokey-webcrypt-tests/files/9675956/firmware.zip)
